34DjangoFramework/bdblog/article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addarticle/',views.addArticle,name="addarticle"),
    path('article/<int:id>',views.detail,name="detail"),
    path('update/<int:id>',views.updateArticle,name="update"),
    path('delete/<int:id>',views.deleteArticle,name="delete"),
    path('',views.articles,name="articles"),
    #içi boş çünkü ana url de artilces gelince buraya bak dedik
    path('comment/<int:id>',views.addComment,name="comment"),
]

34DjangoFramework/bdblog/bdblog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name = "index"), # redirect için name = index
    path('about/', views.about,name = "about"),
    # path('detail/<int:id>', views.detail,name = "detail"),
    # path('articles/deneme1', views.about,name = "about"), # böyle 100 denemeye kadar gidebilir kalıp aynı
    path('articles/',include("article.urls")), #/articles/create gelirse buraya bakar sonra articles.url içine bakar.
    path('user/',include("user.urls")), #user/register vb..
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

34DjangoFramework/bdblog/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),

]

34DjangoFramework/bdblog/article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.


class Article(models.Model):
    #hazır olan djangonun tablosuna atıfta bulunuyoruz # cascade ile o user silinirse tablosu da silinir.
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE,verbose_name="Yazar")
    title = models.CharField(max_length=50,verbose_name="Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturm Tarihi")
    article_image = models.FileField(blank=True,null=True,verbose_name="Makaleye Görsel Ekleyin")
    #veritabanına eklemek için yenilikleri makemigrations(veritabanında tabloyu değiştirdik) daha sonrasında migrate(bunu veritabanında işlemek için)
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['-created_date'] # veritabanında - ile tam tersi duruma çevirilir son eklenen ilk gösterilir
    

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="Makale",related_name="comments") #  article.comments diyerek erişmek için related name verdik
    comment_author = models.CharField(max_length=50,verbose_name="İsim")
    comment_content = models.CharField(max_length=200,verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.comment_author
    
    class Meta:
        ordering = ['-comment_date'] #makemigrations ve migrate yapılmalı veritabanında sağlanması için
    

34DjangoFramework/bdblog/article/forms.py
from django import forms
from .models import Article #input alanı için
class ArticleForm(forms.ModelForm):
    class Meta:# hazır input alanı için django doc bak
        model = Article
        fields = ["title","content","article_image"]

34DjangoFramework/bdblog/article/views.py
import article
from article.models import Article,Comment
from django.shortcuts import redirect, render,HttpResponse,get_object_or_404
from .forms import ArticleForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
# Create your views here.
#url gelince çalışacak fonksiyonlar


# django bölümünde 222. video yorumlarında Articel kullanırken from article.models import Article yapmalısın

def articles(request):

    keyword = request.GET.get("keyword") # name e göre "keyword"

    if (keyword):
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    
    articles = Article.objects.all()

    return render(request,"articles.html",{"articles":articles})


def index(request):
    context = {
        "numbers":[1,2,3,4,5,6]
    }
    return render(request,"index.html",context) # eğer template altında başka bir klasöründe altında ise article/index.html yazılmalı


def about(request):
    return render(request,"about.html")


# def detail(request,id):
#     return HttpResponse("Detail" + str(id))

@login_required(login_url="user:login")
def dashboard(request):

    articles = Article.objects.filter(author = request.user)
    context = {
        "articles" : articles
    }

    return render(request,"dashboard.html",context)
@login_required(login_url="user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if(form.is_valid()):
        
        article = form.save(commit=False)
        article.author = request.user
        article.save()

        """
         article objesini oluşturur article.save() yapar ama user vermemiz lazım
        """
        messages.success(request,"Makale Başarıyla Oluşturuldu")
        return redirect("article:dashboard")


    return render(request,"addarticle.html",{"form":form})

def detail(request,id):
    # article = Article.objects.filter(id = id).first() # liste dönüyor tek obje dönmüyor tek obje almak için first() yazdık
    article = get_object_or_404(Article,id = id)
    comments = article.comments.all()

    return render(request,"detail.html",{"article":article,"comments":comments})
    

@login_required(login_url="user:login")
def updateArticle(request,id):

    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance=article) # instance içine objeyi gönderdik bilgiler article form içine yazılması için
    #instance sayesinde güncelleme sırasında önceki bilgileri aldık
    if(form.is_valid()):
        
        article = form.save(commit=False)
        article.author = request.user
        article.save()

        """
         article objesini oluşturur article.save() yapar ama user vermemiz lazım
        """
        messages.success(request,"Makale Başarıyla Güncellendi.")
        return redirect("article:dashboard")

    return render(request,"update.html",{"form":form})

@login_required(login_url="user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)

    article.delete()

    messages.success(request,"Makale Başarıyla Silindi")

    return redirect("article:dashboard") # artilce uyg altındaki url dosyasına bakar dashboardı döner


def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if(request.method == "POST"):
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        newComment = Comment(comment_author = comment_author,comment_content = comment_content)
        newComment.article = article
        newComment.save()

    # return redirect("/articles/article/"+str(id))

    return redirect(reverse("article:detail",kwargs={"id" : id}))

34DjangoFramework/bdblog/templates/about.html
{% extends "layout.html" %}


{% block body %}

<h3>Hakkımızda</h3>
<hr>

<p>
Lorem ipsum, dolor sit amet consectetur adipisicing elit. Mollitia numquam consequatur nulla eaque? Fugiat nobis, asperiores nam eaque consequuntur ab rerum! Nesciunt provident vero accusamus fugit quae natus tempora cum assumenda et! Voluptatum, nihil ipsam voluptate molestiae pariatur ipsum facere in, dolor minus est accusantium esse obcaecati ab. Nam voluptates officiis, autem eligendi eum tenetur sint ipsa rerum excepturi esse id quae et placeat voluptas nostrum? A temporibus sunt illo dolorem adipisci ducimus qui nesciunt minima rem fuga nisi, impedit animi, eos quidem doloribus, perferendis deleniti tenetur. Quo ipsa eaque accusantium eveniet suscipit! Repellendus iste sunt sint! Asperiores necessitatibus et earum nam assumenda deserunt, inventore vero nisi ad eaque cumque, accusantium quibusdam debitis natus animi, corrupti aliquam beatae dignissimos blanditiis modi. Architecto delectus, commodi maxime suscipit nisi est, exercitationem quaerat maiores harum voluptatem molestias minima autem iure corrupti sed, laborum dolores aut voluptate veritatis inventore atque! Sed delectus distinctio eum.
</p>


{% endblock body %}

34DjangoFramework/bdblog/templates/addarticle.html
{% extends "layout.html" %}


{% block body %}

{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Makale Oluştur</h3>
    <hr>
    <form method = "POST" enctype="multipart/form-data">

        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <br>

        <button type = "submit" class = "btn btn-danger">Oluştur</button>

    </form>
  </div>
</div>





{% endblock body %}

34DjangoFramework/bdblog/templates/articles.html
{% extends 'layout.html' %}



{% block body %}

<div class = "row">
    <div class="col-md-10 offset-md-3">
        <h3>Makaleler</h3>
        <hr>
        <form style = "margin-bottom:20px;"> 
            {% csrf_token %}
            <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Ara..">
            <button type="submit" class="btn btn-danger">Ara</button>
        </form>
        <hr>
    </div>
</div>

{% if articles %}

    {% for article in articles %}
    
        
            <div class="row">
            <div class="col-md-10 offset-md-3">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <a href="{% url 'article:detail' article.id %}"><h3 class="fw-bolder mb-1">{{article.title}}</h3></a>
                            <hr>
                            <p class = "lead">Written By {{article.author}}</p>
                            <!-- Post meta content-->
                            <hr>
                            <div class="text-muted fst-italic mb-2"><strong>{{article.created_date}}</strong></div>
                            <hr>
                        </header>
                        <!-- Preview image figure-->
                        {% if article.article_image %}
                            <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="" /></figure>
                        {% endif %} <!-- bu if eğer article_image yoksa dosyada hata vermesin diye -->

                        <!-- Post content-->

                        <p class ="lead">
                            {{article.content|safe|truncatewords:10}} 
                            <!-- safe ile makale de içerikler html kodu ile değil yazı ile bunlar güvenli anlamında kullanıyoruz.-->
                        </p>
                         <a style = "float : right;" href="{% url 'article:detail' article.id %}" class = "btn btn-danger">Devamını Oku</a>
                        <hr>

                    </article>
                 
                 </div>
            </div>
            </div>
    
    {% endfor %}


{% else %}
<div class ="alert alert-danger">
    Makale Bulunamadı.
</div>
{% endif %}







{% endblock body %}

34DjangoFramework/bdblog/templates/dashboard.html
{% extends "layout.html" %}



{% block body %}

<h3>Kontrol Paneli</h3>
<hr>
<p>
Hoşgeldiniz <small>{{request.user.username}}</small>
</p>
<hr>

<a class="btn btn-danger" href ="/articles/addarticle">Makale Ekle</a>
<hr>

{% if articles %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Başlık</th>
      <th scope="col">Yazar</th>
      <th scope="col">Tarih</th>
      <th scope="col">Güncelle</th>
      <th scope="col">Sil</th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}
    
        <tr>
            <th scope="row">{{article.id}}</th>
            <td> <a href="/articles/article/{{article.id}}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date}}</td>
            <td><a href="/articles/update/{{article.id}}" class = "btn btn-danger">Güncelle</a></td> 
            <td><a href="/articles/delete/{{article.id}}" class = "btn btn-danger">Sil</a></td>  
        </tr>

    {% endfor %}


    <!--<tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td> 
    </tr> -->
    
  </tbody>
</table>
{% else %}

<div class = "alert alert-danger">

Henüz bir makaleniz bulunmuyor.

</div>

{% endif %}




{% endblock body %}

34DjangoFramework/bdblog/templates/detail.html
{% extends "layout.html" %}


{% block body %}

<div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h3 class="fw-bolder mb-1">{{article.title}}</h3>
                            <hr>
                            <p class = "lead">Written By {{article.author}}</p>
                            <!-- Post meta content-->
                            <hr>
                            <div class="text-muted fst-italic mb-2"><strong>{{article.created_date}}</strong></div>
                            <hr>
                        </header>
                        <!-- Preview image figure-->
                        {% if article.article_image %}
                            <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="" /></figure>
                        {% endif %} <!-- bu if eğer article_image yoksa dosyada hata vermesin diye -->

                        <!-- Post content-->

                        <p class ="lead">
                            {{article.content|safe}} 
                            <!-- safe ile makale de içerikler html kodu ile değil yazı ile bunlar güvenli anlamında kullanıyoruz.-->
                        </p>
                        <hr>

                    </article>
                    
                    <h3 class = "font-weight-bold">Comments</h3>
                    <hr>
                    {% if comments %}

                        {% for comment in comments %}
                            <div class="d-flex">
                                <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div style = "margin-bottom : 5px; margin-left : 10px" class="font-weight-bold">{{comment.comment_author}}</div>
                                        <span style = "margin-left : 10px;">{{comment.comment_content}}</span>
                                        <br>
                                        <span style = "margin-left : 10px;">{{comment.comment_date}}</span>
                                </div>
                            </div>
                            <hr>
                        {% endfor %}


                    {% else %}

                        <div class = "alert alert-danger">
                            Herhangi bir yorum yapılmamış.
                        </div>

                    {% endif %}







                        <div class = "card my-4">
                            <h5 class = "card-header">Leave a Comment</h5>
                            <div class = "card-body">
                                <form method = "post" action = "{% url 'article:comment' article.id %}">
                                    {% csrf_token %}
                                    <div class = "form-group">
                                        <label for="authorName" >Your Name:</label>
                                        <input name = "comment_author" type="text" class = "form-control" id = "formGroupInput" placeholder = "Enter your name here...">
                                    </div>
                                    <div class = "form-group">
                                        <label for="authorComment">Comment:</label>
                                        <textarea name ="comment_content" class = "form-control" rows="3" placeholder = "Enter your comment here..."></textarea>
                                    </div> 
                                    <button type = "submit" class = "btn btn-primary">Submit</button> 
                                </form>
                            </div>                 
                        </div>
                </div>
               






{% endblock body %}

34DjangoFramework/bdblog/templates/index.html
{% extends "layout.html" %}


{% block body %}


<div class ="jumbotron text-center">

    <h3>Burak Doğan Kişisel Bloğuna Hoşgeldiniz</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi quidem sint tenetur sit excepturi dignissimos voluptas repellendus quas doloremque ullam.</p>

</div>


<!--{% if number == 20 %}
    <p>sayı 20 dir</p>
{% else %}
    <p>sayı 20 değil</p>
{% endif %}   views içinde gönderdiğmiz context içinde burada if cond-->

<!--<ul>
{% for number in numbers %}
    <li>{{number}}</li>
{% endfor %}
Burada views içinden sayılar gödenrdik ve liste şeklinde bastırdık
</ul> -->

<p>
    {% if request.user.is_authenticated %}
        Giriş Yapılmış, {{request.user.username}}
    {% else %}
        Giriş Yapılmamış
    {% endif %}
</p>



{% endblock body %}

34DjangoFramework/bdblog/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>BdBlog</title>
</head>
<body>
    
    {% include "includes/navbar.html" %}
    
    

    <div style = "margin-top : 100px; margin-bottom : 100px;" class = "container">
        
        {% if messages %}
            
                {% for message in messages %}

                    {% if message.tags == "info" %}
                         <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                         <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                    {% endif %}

                   
                {% endfor %}
            
        {% endif %}


        {% block body %}
        
        
        
        {% endblock body %}
    
    
    
    </div>




    <script src ="{% static 'js/bootstrap.min.js' %}"></script>
    <script src ="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>


</body>
</html>

34DjangoFramework/bdblog/templates/login.html
{% extends "layout.html" %}


{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Giriş Yap</h3>
    <hr>
    <form method = "POST">

        {% csrf_token %}

        {{form|crispy}}
        <br>

        <button type = "submit" class = "btn btn-danger">Giriş Yap</button>

    </form>
  </div>
</div>


{% endblock body %}

34DjangoFramework/bdblog/templates/register.html
{% extends "layout.html" %}


{% block body %}

{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Giriş Yap</h3>
    <hr>
    <form method = "POST">

        {% csrf_token %}

        {{form|crispy}}
        <br>

        <button type = "submit" class = "btn btn-danger">Kayıt ol</button>

    </form>
  </div>
</div>


{% endblock body %}

34DjangoFramework/bdblog/templates/update.html
{% extends "layout.html" %}


{% block body %}

{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Makale Güncelle</h3>
    <hr>
    <form method = "POST" enctype="multipart/form-data">

        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <br>

        <button type = "submit" class = "btn btn-danger">Güncelle</button>

    </form>
  </div>
</div>





{% endblock body %}